services:
  _defaults:
    autowire: true

  # This service is set after the container is created
  ICanBoogie\Application:
    synthetic: true

  ICanBoogie\ConfigProvider:
    factory: [ '@service_accessor', get ]
    arguments: [ configs ]

  ICanBoogie\ServiceProvider:
    alias: ICanBoogie\Application

  # helpers to access services available as application's properties

  service_accessor:
    class: ICanBoogie\Binding\SymfonyDependencyInjection\ServiceAccessor

  app.vars:
    class: ICanBoogie\Storage\Storage
    factory: [ '@service_accessor', get ]
    arguments: [ vars ]
